/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Consumer;

import Business.Business.EcoSystem;
import Business.Employee.Consumer;
import Business.Enterprise.Enterprise;
import Business.Organization.ConsumerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Vishwa
 */
public class ConsumerWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization consumerOrganization;
    private Enterprise enterprise;
    private EcoSystem system;
    private Consumer consumer;

    /**
     * Creates new form ConsumerWorkAreaJPanel
     */
    public ConsumerWorkAreaJPanel(JPanel userProcessContainer,UserAccount account, Organization organization,Enterprise enterprise,Consumer consumer,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.consumerOrganization = (ConsumerOrganization)organization;
        this.enterprise = enterprise;
        this.consumer = consumer;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageProfileJButton = new javax.swing.JButton();
        browseAWebsiteJButton = new javax.swing.JButton();
        openAWebsiteJButton = new javax.swing.JButton();
        clicksOnAdvertisementJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));

        manageProfileJButton.setText("Manage Profile");
        manageProfileJButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        manageProfileJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProfileJButtonActionPerformed(evt);
            }
        });

        browseAWebsiteJButton.setText("Browse A Website");
        browseAWebsiteJButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        browseAWebsiteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseAWebsiteJButtonActionPerformed(evt);
            }
        });

        openAWebsiteJButton.setText("Open A Website");
        openAWebsiteJButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        openAWebsiteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAWebsiteJButtonActionPerformed(evt);
            }
        });

        clicksOnAdvertisementJButton.setText("Clicks On Advertisement");
        clicksOnAdvertisementJButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        clicksOnAdvertisementJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicksOnAdvertisementJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clicksOnAdvertisementJButton)
                    .addComponent(openAWebsiteJButton)
                    .addComponent(browseAWebsiteJButton)
                    .addComponent(manageProfileJButton))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(manageProfileJButton)
                .addGap(18, 18, 18)
                .addComponent(browseAWebsiteJButton)
                .addGap(18, 18, 18)
                .addComponent(openAWebsiteJButton)
                .addGap(18, 18, 18)
                .addComponent(clicksOnAdvertisementJButton)
                .addContainerGap(152, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageProfileJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProfileJButtonActionPerformed

        ManageProfileJPanel mpjp = new ManageProfileJPanel(userProcessContainer,consumer,consumerOrganization);
        userProcessContainer.add("ManageProfileJPanel", mpjp);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_manageProfileJButtonActionPerformed

    private void openAWebsiteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openAWebsiteJButtonActionPerformed
        WebsiteJPanel wjp = new WebsiteJPanel(userProcessContainer, system,account, consumer,consumerOrganization);
        userProcessContainer.add("WebsiteJPanel", wjp);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_openAWebsiteJButtonActionPerformed

    private void browseAWebsiteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseAWebsiteJButtonActionPerformed

        BrowseAWebsiteJPanel baw = new BrowseAWebsiteJPanel(userProcessContainer, consumer,system);
        userProcessContainer.add("BrowseAWebsiteJPanel", baw);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_browseAWebsiteJButtonActionPerformed

    private void clicksOnAdvertisementJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicksOnAdvertisementJButtonActionPerformed
        ClickingOnAdvertisementJPanel coajp = new ClickingOnAdvertisementJPanel(userProcessContainer,system,consumer);
        userProcessContainer.add("ClickingOnAdvertisementJPanel", coajp);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_clicksOnAdvertisementJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseAWebsiteJButton;
    private javax.swing.JButton clicksOnAdvertisementJButton;
    private javax.swing.JButton manageProfileJButton;
    private javax.swing.JButton openAWebsiteJButton;
    // End of variables declaration//GEN-END:variables
}
