/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Marketing;

import Business.Business.EcoSystem;
import Business.Employee.Marketer;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.Auction.AuctionJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Vishwa
 */
public class MarketerWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Marketer marketer;
    private Organization marketingOrganization;
    private UserAccount account;
    private EcoSystem system;

    /**
     * Creates new form MarketerWorkAreaJPanel
     */
    public MarketerWorkAreaJPanel(JPanel userProcessContainer,Marketer marketer,Organization organization,UserAccount account,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.marketer = marketer;
        this.marketingOrganization = organization;
        this.account = account;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageBiddingModelJButton = new javax.swing.JButton();
        viewBiddingJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));

        manageBiddingModelJButton.setText("Manage Bidding Model >>");
        manageBiddingModelJButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 255)));
        manageBiddingModelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBiddingModelJButtonActionPerformed(evt);
            }
        });

        viewBiddingJButton.setText("View Bidding >>");
        viewBiddingJButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 255)));
        viewBiddingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBiddingJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewBiddingJButton)
                    .addComponent(manageBiddingModelJButton))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(manageBiddingModelJButton)
                .addGap(18, 18, 18)
                .addComponent(viewBiddingJButton)
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageBiddingModelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBiddingModelJButtonActionPerformed
        ManageBiddingModelJPanel mbm = new ManageBiddingModelJPanel(userProcessContainer,marketer);
        userProcessContainer.add("ManageBiddingModelJPanel",mbm);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_manageBiddingModelJButtonActionPerformed

    private void viewBiddingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBiddingJButtonActionPerformed
//        marketer.accesingAdExchange();
        AuctionJPanel awajp = new AuctionJPanel(userProcessContainer);
        userProcessContainer.add("AuctionWorkAreaJPanel",awajp);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_viewBiddingJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manageBiddingModelJButton;
    private javax.swing.JButton viewBiddingJButton;
    // End of variables declaration//GEN-END:variables
}
