/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Publisher;

import Business.Employee.Publisher;
import Business.Publisher.Page;
import java.awt.CardLayout;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vishwa
 */
public class ManageSpaceJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Publisher publisher;

    /**
     * Creates new form ManageSpaceJPanel
     */
    public ManageSpaceJPanel(JPanel userProcessContainer,Publisher publisher) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.publisher = publisher;
        populateComboBox();
        groupButton();
        spaceLabel1.setVisible(false);
        spaceLabel2.setVisible(false);
        spaceLabel3.setVisible(false);
        
    }
    
    private void populateComboBox()
    {
        pageJComboBox.removeAllItems();
        for(Page page : publisher.getPageCatalog().getPageList())
        {
            pageJComboBox.addItem(page);
        }
    }
    
     private void groupButton()
    {
        ButtonGroup bg = new ButtonGroup();
        bg.add(haveSpaceJRadioButton);
        bg.add(noSpaceJRadioButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pageJLabel = new javax.swing.JLabel();
        pageJComboBox = new javax.swing.JComboBox();
        heightJLabel = new javax.swing.JLabel();
        breadthJLabel = new javax.swing.JLabel();
        heightJTextField = new javax.swing.JTextField();
        breadthJTextField = new javax.swing.JTextField();
        addJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        haveSpaceJRadioButton = new javax.swing.JRadioButton();
        noSpaceJRadioButton = new javax.swing.JRadioButton();
        refreshJButton = new javax.swing.JButton();
        basePriceJLabel = new javax.swing.JLabel();
        basePriceJTextField = new javax.swing.JTextField();
        spaceLabel1 = new javax.swing.JLabel();
        spaceLabel2 = new javax.swing.JLabel();
        spaceLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));

        pageJLabel.setText("Page:");
        pageJLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));

        pageJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pageJComboBox.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));

        heightJLabel.setText("Height:");
        heightJLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));

        breadthJLabel.setText("Breadth:");
        breadthJLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));

        heightJTextField.setBackground(new java.awt.Color(240, 240, 240));
        heightJTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        heightJTextField.setEnabled(false);

        breadthJTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        breadthJTextField.setEnabled(false);

        addJButton.setText("Add");
        addJButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        haveSpaceJRadioButton.setText("Have Space");
        haveSpaceJRadioButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        haveSpaceJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haveSpaceJRadioButtonActionPerformed(evt);
            }
        });

        noSpaceJRadioButton.setText("No Space");
        noSpaceJRadioButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        noSpaceJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noSpaceJRadioButtonActionPerformed(evt);
            }
        });

        refreshJButton.setText("Refresh");
        refreshJButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        basePriceJLabel.setText("Set Base Price:");
        basePriceJLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));

        basePriceJTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        basePriceJTextField.setEnabled(false);

        spaceLabel1.setText("Space has already been created");
        spaceLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));

        spaceLabel2.setText("Space has already been created");
        spaceLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));

        spaceLabel3.setText("Space has already been created");
        spaceLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(haveSpaceJRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(noSpaceJRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addJButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(refreshJButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pageJLabel)
                                                    .addComponent(heightJLabel)
                                                    .addComponent(breadthJLabel))
                                                .addGap(117, 117, 117))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(basePriceJLabel)
                                                .addGap(87, 87, 87)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pageJComboBox, 0, 100, Short.MAX_VALUE)
                                            .addComponent(heightJTextField)
                                            .addComponent(breadthJTextField)
                                            .addComponent(basePriceJTextField))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spaceLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(spaceLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spaceLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pageJLabel)
                    .addComponent(pageJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(haveSpaceJRadioButton)
                    .addComponent(noSpaceJRadioButton))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightJLabel)
                    .addComponent(heightJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spaceLabel1))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breadthJLabel)
                    .addComponent(breadthJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spaceLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basePriceJLabel)
                    .addComponent(basePriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spaceLabel3))
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addJButton)
                    .addComponent(refreshJButton))
                .addGap(18, 18, 18)
                .addComponent(backJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        try{
        if(haveSpaceJRadioButton.isSelected())
        {
            Page page = (Page)pageJComboBox.getSelectedItem();
            page.setSpace(true);
            double height = Float.parseFloat(heightJTextField.getText());
            double breadth = Float.parseFloat(breadthJTextField.getText());
            double basePrice = Float.parseFloat(basePriceJTextField.getText());
        
            publisher.getAdSpaceInventory().addAdSpace();
            page.getAdSpace().setHeight(height);
            page.getAdSpace().setBreadth(breadth);
            page.getAdSpace().setBasePrice(basePrice);
            page.getAdSpace().setProbability(0.5);
        }
        else if(noSpaceJRadioButton.isSelected())
        {
            Page page = (Page)pageJComboBox.getSelectedItem();
            page.setSpace(false);
            publisher.getAdSpaceInventory().addAdSpace();
            page.getAdSpace().setHeight(0);
            page.getAdSpace().setBreadth(0);
            page.getAdSpace().setBasePrice(0);
            page.getAdSpace().setProbability(0);
        }}
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Enter in a valid Format");
            return;
        }
          
        
    }//GEN-LAST:event_addJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        ((CardLayout)userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void haveSpaceJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haveSpaceJRadioButtonActionPerformed
        Page page = (Page)pageJComboBox.getSelectedItem();
        if(page.isSpace() == true)
        {
            heightJTextField.setEnabled(false);
            breadthJTextField.setEnabled(false);
            basePriceJTextField.setEnabled(false);
            
            spaceLabel1.setVisible(true);
            spaceLabel2.setVisible(true);
            spaceLabel3.setVisible(true);
        }
        else if(page.isSpace() == false)
        {
            heightJTextField.setEnabled(true);
            breadthJTextField.setEnabled(true);
            basePriceJTextField.setEnabled(true);
            
            spaceLabel1.setVisible(false);
            spaceLabel2.setVisible(false);
            spaceLabel3.setVisible(false);
        }
        
        
   
    }//GEN-LAST:event_haveSpaceJRadioButtonActionPerformed

    private void noSpaceJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noSpaceJRadioButtonActionPerformed
        heightJTextField.setEnabled(false);
        breadthJTextField.setEnabled(false);
        basePriceJTextField.setEnabled(false);
        
        spaceLabel1.setVisible(false);
        spaceLabel2.setVisible(false);
        spaceLabel3.setVisible(false);
        
        heightJTextField.setText("");
        breadthJTextField.setText("");
        basePriceJTextField.setText("");
        
    }//GEN-LAST:event_noSpaceJRadioButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        groupButton();
            heightJTextField.setText("");
            breadthJTextField.setText("");
            basePriceJTextField.setText("");
            
            heightJTextField.setEnabled(false);
            breadthJTextField.setEnabled(false);
            basePriceJTextField.setEnabled(false);
        
    }//GEN-LAST:event_refreshJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel basePriceJLabel;
    private javax.swing.JTextField basePriceJTextField;
    private javax.swing.JLabel breadthJLabel;
    private javax.swing.JTextField breadthJTextField;
    private javax.swing.JRadioButton haveSpaceJRadioButton;
    private javax.swing.JLabel heightJLabel;
    private javax.swing.JTextField heightJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton noSpaceJRadioButton;
    private javax.swing.JComboBox pageJComboBox;
    private javax.swing.JLabel pageJLabel;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JLabel spaceLabel1;
    private javax.swing.JLabel spaceLabel2;
    private javax.swing.JLabel spaceLabel3;
    // End of variables declaration//GEN-END:variables
}
