/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Advertiser;

import Business.Business.EcoSystem;
import Business.Employee.Advertiser;
import Business.Enterprise.Enterprise;
import Business.Organization.AdvertisingOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vishwa
 */
public class AdvertiserWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization advertiserOrganization;
    private Enterprise enterprise;
    private Advertiser advertiser;
    private EcoSystem system;

    /**
     * Creates new form AdvertiserWorkAreaJPanel
     */
    public AdvertiserWorkAreaJPanel(JPanel userProcessContainer,UserAccount account,Organization organization,Enterprise enterprise,Advertiser advertiser,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.advertiserOrganization = (AdvertisingOrganization)organization;
        this.enterprise = enterprise;
        this.advertiser = advertiser;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        manageProductJButton = new javax.swing.JButton();
        viewAdCatalogJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fieldJTextField = new javax.swing.JTextField();
        enterJButton = new javax.swing.JButton();
        manageAdvertisementJButton = new javax.swing.JButton();
        companyNameJLabel = new javax.swing.JLabel();
        companyNameJTextField = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));

        manageProductJButton.setText("Manage Product >> ");
        manageProductJButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        manageProductJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductJButtonActionPerformed(evt);
            }
        });

        viewAdCatalogJButton.setText("View Ad Catalog >>");
        viewAdCatalogJButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        viewAdCatalogJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAdCatalogJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Field:");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));

        fieldJTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));

        enterJButton.setText("Enter");
        enterJButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        enterJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterJButtonActionPerformed(evt);
            }
        });

        manageAdvertisementJButton.setText("Manage Advertisement >>");
        manageAdvertisementJButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        manageAdvertisementJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdvertisementJButtonActionPerformed(evt);
            }
        });

        companyNameJLabel.setText("Company Name:");
        companyNameJLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));

        companyNameJTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewAdCatalogJButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(enterJButton)
                        .addComponent(manageProductJButton))
                    .addComponent(manageAdvertisementJButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(companyNameJLabel))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(companyNameJTextField))))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyNameJLabel)
                    .addComponent(companyNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(enterJButton)
                .addGap(34, 34, 34)
                .addComponent(manageProductJButton)
                .addGap(18, 18, 18)
                .addComponent(manageAdvertisementJButton)
                .addGap(18, 18, 18)
                .addComponent(viewAdCatalogJButton)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageProductJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductJButtonActionPerformed
        ManageProductJPanel mpjp = new ManageProductJPanel(userProcessContainer,advertiserOrganization,advertiser);
        userProcessContainer.add("ManageProductJPanel",mpjp);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_manageProductJButtonActionPerformed

    private void viewAdCatalogJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAdCatalogJButtonActionPerformed
        ViewAdCatalogJPanel vacjp = new ViewAdCatalogJPanel(userProcessContainer,advertiser);
        userProcessContainer.add("ViewAdCatalogJPanel",vacjp);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_viewAdCatalogJButtonActionPerformed

    private void enterJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterJButtonActionPerformed
        try{
        String name = companyNameJTextField.getText();
        String field = fieldJTextField.getText();
        if(name.isEmpty() || name.equals(null) || name.trim().isEmpty() && field.isEmpty() || field.equals(null) || field.trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Enter a valid String");
            return;
        }
        else{
        advertiser.setCompanyName(name);
        advertiser.setField(field);
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Enter a Valid String");
            return;
        }
    }//GEN-LAST:event_enterJButtonActionPerformed

    private void manageAdvertisementJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdvertisementJButtonActionPerformed
        ManageAdvertisementJPanel majp = new ManageAdvertisementJPanel(userProcessContainer, advertiser,system);
        userProcessContainer.add("ManageAdvertisementJPanel",majp);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_manageAdvertisementJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel companyNameJLabel;
    private javax.swing.JTextField companyNameJTextField;
    private javax.swing.JButton enterJButton;
    private javax.swing.JTextField fieldJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton manageAdvertisementJButton;
    private javax.swing.JButton manageProductJButton;
    private javax.swing.JButton viewAdCatalogJButton;
    // End of variables declaration//GEN-END:variables
}
